<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>
<html>
    <head>
        <link href="<c:url value="/resources/css/colombia.css" />" rel="stylesheet">
        <title>::Colombia::</title>
    </head>
    <body>
        <h1>Cambio climático en Colombia</h1>
        <nav>
            <a href="intro">Inicio</a>
            <a href="colombia">Colombia</a>
            <a href="problematic">ODS</a>
            <a href="methodology">Metodología</a>
            <a href="news">Noticias</a>
            <div class="animation start-home"></div>
        </nav>
        <hr>
        <div style="margin: auto;margin-top: 0px;width: 1800px;height: 500px;">
            <div style="width: 600px;height: 500px;float: left;">
                <iframe width="600" height="500" src="https://www.youtube.com/embed/SX0MGvyz4v4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            </div>
            <div style="width: 1200px;height: 500px;float: left;">
                <%@ include file="/resources/html/colombia1.html" %>
            </div>
        </div>
        <hr>
        <div style="margin: auto;margin-top: 0px;width: 1800px;height: 3000px;">
            <h3 id ="text"><p>¿Cuáles son los efectos del cambio climático en Colombia? En marzo de 2018, la NASA publicó un video en el que muestra cómo <strong>toneladas de polvo viajan desde el desierto del Sahara hasta el Amazonas</strong>, un recorrido impulsado por vientos que pueden alcanzar la velocidad de cinco mil kilómetros por hora a través del océano Atlántico y que llevan fósforo a la selva suramericana, donde las plantas necesitan de este nutriente para sobrevivir.&nbsp;Entre tanto, en la selva ocurre la evapotranspiración, un fenómeno en el cual el agua vuelve a la atmósfera por su evaporación desde el suelo y por la transpiración de las plantas. En forma de vapor, es llevada por el viento desde el Amazonas hacia otras regiones que necesitan de esta humedad para evitar la sequía y mantener vivos sus ecosistemas. En Colombia, viaja hacia la cordillera de Los Andes, donde <strong>retorna al suelo en forma de lluvia</strong> y llena los embalses que surten a las grandes ciudades.</p>
            <p>Los científicos Carlos Nobre y Thomas Lovejoy, autoridades mundiales a la hora de hablar del Amazonas, publicaron el pasado mes de febrero en la revista <a href="http://advances.sciencemag.org/content/4/2/eaat2340" target="_blank"><span style="text-decoration: underline;"><em>Science Advance</em></span></a> un artículo en el que revelan que la deforestación está llevando a esta región a un punto sin retorno, en el cual ya no cumpliría su rol en el ciclo hidrológico. Las lluvias disminuirían y esto traería repercusiones negativas. La investigación revela que <strong>la deforestación ha acabado con el 17 por ciento de la vegetación de la región</strong> y, que si alcanza el 20 por ciento, la selva puede pasar de ser el sostén de los ecosistemas a convertirse en una extensa y árida sabana.</p>
            <p>Rodrigo Botero, director de la Fundación para la Conservación y el Desarrollo Sostenible, <a href="http://fcds.org.co/" target="_blank"><span style="text-decoration: underline;">FCDS</span></a>, hace sobrevuelos cada cuarenta días en la región amazónica y confirma la información arrojada por el estudio de Nobre y Lovejoy. ?Esto está cerca de llegar a un punto de inflexión en el que va a haber una región deforestada, seca, sin vegetación, desde la que ya no va a subir tanta agua como antes a Los Andes y va a empezar a verse una crisis significativa?, dice, refiriéndose al nivel de industrialización y urbanización de la región central del país, que depende de un buen suministro de este recurso y de energía, cuya producción también está ligada mayoritariamente al agua.</p>
            <p>Botero asegura que actualmente hay todo tipo de actores apropiándose de las tierras de la Amazonía y la Orinoquía de manera ilícita, comprándolas en un mercado informal, para quemar el bosque y usar el terreno deforestado en actividades económicas como la ganadería y la siembra extensiva de cultivos legales e ilegales. El ambientalista también explica que esta región es una de las de mayor biodiversidad en el mundo, de la cual depende la riqueza en varios sentidos. ?<strong>Cuando hablamos de erosión genética (pérdida de diversidad genética) estamos hablando de pobreza</strong>. Entre menos especies tengas, menos biodiversidad y esto puede colapsar. Esos ecosistemas funcionan gracias a su complejidad?, afirma.</p>
            <p style="text-align: center;"><img src="http://fcds.org.co/site/wp-content/uploads/2011/08/34955_1-1200x630.jpg" alt="" width="1000" height="668"></p>
            <p><strong>La deforestación parece ser una de las causantes de la aceleración del incremento de la temperatura de la Tierra</strong>, el fenómeno característico del cambio climático. La ciencia concuerda en su mayoría en que dicho aceleramiento es consecuencia del aumento de emisiones de gases de efecto invernadero, GEI, producido también por actividades realizadas por la humanidad como la quema de combustibles fósiles -carbón, petróleo y gas-.</p>
            <p>Aunque existen científicos convencidos de que no es la acción humana la causa del aumento acelerado de la temperatura, pues aseguran que no hay estudios científicos rigurosos para demostrar que los cambios recientes son inusuales en comparación con los registros históricos del planeta, <strong>lo cierto es que son innegables las evidencias del calentamiento</strong>, con hechos como el derretimiento de los glaciares y los nevados. Según la NASA, la temperatura media de la superficie terrestre aumentó 0,8 grados centígrados de 1880 a 2015.</p>
            El cambio climático afecta la biodiversidad
            <p><strong>Los cambios de temperatura afectan la distribución, el tamaño, la estructura y la abundancia de las poblaciones de algunas especies</strong>, como lo publicó la CEPAL el año pasado en su informe <a href="https://repositorio.cepal.org/bitstream/handle/11362/39855/S1501295_en.pdf?sequence=1" target="_blank"><span style="text-decoration: underline;">?El cambio climático y sus efectos en la biodiversidad de América Latina?</span></a>, basado en evidencia científica. Esto, en otras palabras, representa cambios en la biodiversidad.&nbsp;</p>
            <p>María Eugenia Rinaudo, del <a href="http://www.humboldt.org.co/es/" target="_blank"><span style="text-decoration: underline;">Instituto de Investigación de Recursos Biológicos Alexander von Humboldt</span></a>, explica que cuando se habla de biodiversidad también se habla de servicios ecosistémicos. La Organización de las Naciones Unidas para la Alimentación y la Agricultura, <a href="http://www.fao.org/home/es/" target="_blank"><span style="text-decoration: underline;">FAO</span></a>, los define como la multitud de beneficios que la naturaleza aporta a la sociedad, al proporcionar alimentos nutritivos y agua limpia; al regular las enfermedades y el clima; al apoyar la polinización de los cultivos y la formación de suelos, y al ofrecer beneficios recreativos, culturales y espirituales.&nbsp;</p>
            <p>La experta en biodiversidad del Humboldt hace énfasis en <strong>el riesgo que representa el cambio climático para la polinización</strong>, el proceso de la naturaleza que permite la germinación y la aparición de nuevos frutos y semillas y que ya está en riesgo. Investigaciones de diferentes organizaciones como la FAO o la Plataforma Intergubernamental Científico-Normativa sobre Diversidad Biológica y Servicios de los Ecosistemas, <a href="http://www.biodiversidad.gob.mx/planeta/internacional/ipbes.html" target="_blank"><span style="text-decoration: underline;">IPBES</span></a>, han prendido alarmas por el declive en el número de especies polinizadoras como las abejas, en peligro de extinción. ?La polinización es vital para la producción de alimentos y los medios de vida de los seres humanos y vincula directamente los ecosistemas silvestres y los sistemas de producción agrícola?, explica Rinaudo.</p>
            <p style="text-align: center;"><img src="http://www.todoesciencia.gov.co/sites/default/files/06_cambio_nieve_ruiz.jpg" alt="" width="1000" height="614"></p>
            ¿Cómo se reacciona al cambio climático en Colombia?
            <p>El Instituto de Hidrología, Meteorología y Estudios Ambientales de Colombia, <a href="http://www.ideam.gov.co/" target="_blank"><span style="text-decoration: underline;">IDEAM</span></a>, dice que la evidencia histórica muestra un <strong>aumento significativo en las sequías y en las precipitaciones extremas</strong> en los últimos treinta años y se pronostica un incremento de cerca de 0,9 grados centígrados para el 2040 y de 2,4 grados centígrados a final de siglo en la temperatura del país.</p>
            <p>La información proviene de la <a href="http://documentacion.ideam.gov.co/openbiblio/bvirtual/023731/TCNCC_COLOMBIA_CMNUCC_2017_2.pdf" target="_blank"><span style="text-decoration: underline;">tercera comunicación nacional de cambio climático</span></a> (2017), el mecanismo en el cual se analiza la vulnerabilidad de Colombia ante este fenómeno planetario y que busca servir como herramienta para la gestión territorial. Allí se hacen proyecciones de cómo se pueden ver afectados el recurso hídrico, el hábitat humano, la biodiversidad, la infraestructura, la salud y la seguridad alimentaria. Según el documento, <strong>el 100 por ciento de los municipios de Colombia tiene algún grado de riesgo por cambio climático</strong> y en 2040 el 25 por ciento estará en riesgo alto y muy alto de sufrir fuertes impactos.</p><p>En relación con estos datos, varias entidades públicas vienen trabajando para tomar acciones que mitiguen los efectos del cambio climático. El año pasado, el Ministerio de Ambiente y Desarrollo Sostenible publicó <a href="http://www.minambiente.gov.co/index.php/politica-nacional-de-cambio-climatico-2#politica-nacional-de-cambio-climatico-pncc" target="_blank"><span style="text-decoration: underline;">el documento</span></a> para tomadores de decisiones de la Política Nacional de Cambio Climático, en la cual se plantean las <strong>metas nacionales de desarrollo</strong> bajo en carbono y resiliente al clima, con el objetivo de reducir los riesgos y aprovechar las oportunidades.</p>
            <p>En relación con estos datos, varias entidades públicas vienen trabajando para tomar acciones que mitiguen los efectos del cambio climático. El año pasado, el Ministerio de Ambiente y Desarrollo Sostenible publicó <a href="http://www.minambiente.gov.co/index.php/politica-nacional-de-cambio-climatico-2#politica-nacional-de-cambio-climatico-pncc" target="_blank"><span style="text-decoration: underline;">el documento</span></a> para tomadores de decisiones de la Política Nacional de Cambio Climático, en la cual se plantean las <strong>metas nacionales de desarrollo</strong> bajo en carbono y resiliente al clima, con el objetivo de reducir los riesgos y aprovechar las oportunidades.</p>
            <p>A estos documentos se suman otros como los resultantes de una <a href="https://www.dnp.gov.co/programas/ambiente/CambioClimatico/Paginas/Cambio-Climatico.aspx" target="_blank"><span style="text-decoration: underline;">agenda de investigación</span></a> del Departamento de Planeación Nacional, con <strong>análisis económicos sobre las implicaciones del cambio económico en el país</strong>. Por ejemplo, en los precios del agua, en los efectos económicos de futuras sequías y en las implicaciones negativas para el sector forestal, ganadero y transporte, entre otros.</p>
            <p>También es un fenómeno contemplado en el <a href="http://www.cambioclimatico.gov.co" target="_blank"><span style="text-decoration: underline;">Plan Nacional de Desarrollo 2014-2018</span></a>. De hecho, en 2016 se creó por decreto el Sistema Nacional de Cambio Climático, <a href="http://www.minambiente.gov.co/images/normativa/app/decretos/55-decreto%20298%20feb%202016.pdf" target="_blank"><span style="text-decoration: underline;">Sisclima</span></a>, un conjunto de entidades estatales privadas y sin animo lucro, de políticas, normas, procesos, recursos, planes, estrategias, instrumentos y mecanismos, así como de información atinente al cambio climático, que se aplica de manera organizada para <strong>gestionar la mitigación de gases efecto invernadero y la adaptación al cambio climático en el país</strong>.</p>
            <p style="text-align: center;"><img src="http://www.todoesciencia.gov.co/sites/default/files/04_cambio_climatico_colombia_sierra_nevada_santa_marta.jpg" alt="" width="1000" height="668"></p>
            <p>Mejor dicho, en el papel están contemplados los riesgos para Colombia y se proponen acciones para enfrentarlos. Sin embargo, pasar a la acción requiere de un esfuerzo por parte de las entidades públicas, privadas y de la ciudadanía. ?<strong>La presión social es importante</strong>?, dice Rodrigo Botero de la FCDS, haciendo referencia a cómo logró frenarse el pasado mes de marzo la construcción de la Marginal de la Selva, una carretera pensada desde 1960, que recortaría 381 kilómetros entre San Vicente del Caguán y San José del Guaviare, con impactos negativos medioambientales para la zona. ?<strong>Eso no es que un señor de casco blanco venga a decir que los ambientalistas están frenando el desarrollo del país</strong>. Esto está asociado a lo que llamamos conectividad (entre las regiones). Es conservar bosques biodiversos que van a permitir mantener esto para nuestros tataranietos?, dice.&nbsp;</p>
            <p>Para María Eugenia Rinaudo, la experta del Humboldt, es indispensable proponer formas de gestionar la biodiversidad y explica que, al ver las estadísticas globales de tendencia de gases de efecto invernadero, estas están relacionadas con la producción de bienes y servicios. ?<strong>Hay que cambiar esa conciencia energética y eso no lo va a poder hacer un solo ciudadano, sino que es un tema político</strong>. Lo que sí puede hacer la gente es desarrollar hábitos hacia otras cosas. Por ejemplo, consumir más local, tratar de ser más eficientes en ese aspecto. Creo que la gente poco a poco va a cambiar ese chip?, concluye.&nbsp;</p>
            Acciones cotidianas para mitigar el cambio climático&nbsp;
            <p>Si bien intervenir directamente en las políticas ambientales es algo que los ciudadanos no pueden hacer siempre desde sus vidas cotidianas, hay una serie de acciones que cooperan a cambiar el chip que menciona la experta del Humboldt hacia una vida más consciente del rol de los seres humanos en el cambio climático, principalmente desde el consumo local de bienes y servicios. Estas son algunas recomendaciones<span style="font-size: 13.008px;">:</span>&nbsp;</p>
            <p><strong>Movilidad:</strong> usar el transporte público y los paraderos, vehículos compartidos e incrementar el uso de la bicicleta.</p>
            <p><strong>En el campo:</strong> cuidar árboles, aún en épocas de sequía, cocinar con estufas de leña eficientes y recolectar agua.</p>
            <p><strong>En la oficina:</strong> reducir las impresiones, apagar los equipos electrónicos cuando no estén en uso, pasarse a los bombillos ahorradores o LED.</p>  
            <p><strong>En la oficina:</strong> reducir las impresiones, apagar los equipos electrónicos cuando no estén en uso, pasarse a los bombillos ahorradores o LED.</p>            
            </h3>

        </div>        
        
        

</body>